[package]
name = "cv-ats-gen"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
opt-level = "z"
strip = true
panic = "abort"

[dependencies]
maud = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tiny_http = "0.12"
urlencoding = "2.1"
